In [6]:
import pandas as pd
import glob

path = r'D:\Techlogix\Predefined_Models' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

In [7]:
frame.head(
)

,number,kW,Load Detected,AC Detected,Motor,Microwave,result,Time,Sr
0,NaN,1.454,0,0,0,0,0,NaN,NaN
1,NaN,1.442,0,0,0,0,0,NaN,NaN
2,NaN,1.455,0,0,0,0,0,NaN,NaN
3,NaN,1.453,0,0,0,0,0,NaN,NaN
4,NaN,1.357,0,0,0,0,0,NaN,NaN